### PR TITLE
[WIP] Fresh

### PR DESCRIPTION
**Pull request by dev4dev**
Hi guys, thanks for your component. 

I ran into a bug recently, when after several consequent calls to showOrUpdateHUD and then removeHUD, the HUD remains on screen. I fixed it in https://github.com/dev4dev/APESuperHUD/commit/aa1696605fd21b05c400606005c1c75039251c7d. But then a decided to cleanup API a little bit and ended up with following code in this PR. Would you mind to look through it and comment what do you think. There are still few edge cases like `showMessages` method (which I consider as not so helpful IRL), which should be fixed or removed completely. And types naming isn't perfect yet.

Cheers.

### CODE REVIEW

**Comment by dev4dev** [comment]
Hello, is anybody alive? =)

**Comment by eFagerman** [comment]
Hi, sorry for Very late response. I will look at the pull request :)

**Comment by eFagerman** [comment]
Hi, I looked at the PR and also talked with colleagues. We think the new API looks good (more Swifty). However can you make sure the PR also passes through all unit tests?

**Comment by eFagerman** [comment]
Hi again, can you create a new PR to the Develop branch instead of Master.

**Comment by dev4dev** [comment]
Hello, I'm a little bit busy atm, I'll give it a look asap
Cheers

**Comment by dev4dev** [comment]
Hello,

I've updated it, fixed tests. But I still do not see any sense in those `funny messages`, thus I've not implemented them. And dismiss behavior changed a little bit, now it should be specified explicitly, it wont automatically dismiss if you show message with a checkmark icon, as it was before.

**Comment by eFagerman** [comment]
Hi, 
Thanks! I will take a final look at your PR.

**Comment by dev4dev** [comment]
@erifa  there are still few commented parts, related to `funny messages`, they should be cleaned out, if it's ok to ditch it.

**Pull request closed without merging**
